### ISSUE TITLE
/sys/default/client/scripts/installServerTode2/ should be split out

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/gsDevKitHome#38]
for folks with existing stone structures, the code between the backups in /sys/default/client/scripts/installServerTode2/ needs to be run ... would be convenient to split that out ahead of time so that a single command can be documented as the conversion method:

jUst for grins here's the code of interest:

```Shell
# Set up /sys node structure
mount --todeRoot sys/default /sys default
mount --todeRoot sys/local /sys local
mount --todeRoot sys/stones /sys stones
# ensure that --stoneRoot directory structure is present
/sys/default/bin/validateStoneSysNodes --files --repair
mount --stoneRoot / /sys stone
# Define /home and /projects based on a composition of the /sys nodes
mount --stoneRoot homeComposition.ston / home
mount --stoneRoot projectComposition.ston / projects

```

**Comment by krono** [comment]
I just installed a new Tode and the `/sys` node is not present.

Probably the code mentioned has to be doctumented in the install process or, actually, be run?

**Comment by dalehenrich** [comment]
The new script file is tode/sys/default/client/scripts/setUpSys ...

@krono all of this work is taking place on the dev branch and will be available for general use when I announce the release GsDevKitHome v1.0.0 and tODE v0.0.3 ... both will be released together
