### ISSUE TITLE
`Do not clone as root` ... 

### ISSUE THREAD

**Issue by dalehenrich** [GsDevKit/gsDevKitHome#48]
It is worth mentioning that when the initial clone is made there is no need to run the clone as root and that it should be cloned such that the normal user has write permissions ... `sudo` is used where and when `root` operations are performed

**Comment by krono** [comment]
I think, “do not run as `root`” is too much, just a clarification
of the the implications should suffice (like clone as root -> run everything else as root…)

**Comment by dalehenrich** [comment]
@krono, thanks for the suggestion:)
