### ISSUE TITLE
Support ubuntu 16.04

### ISSUE THREAD

**Issue by laheadle** [GsDevKit/gsDevKitHome#92]
#  GsDevKit script: osPrereqs -X

unrecognized Ubuntu version 16.04
  USAGE: osPrereqs [-h] [-X] [-G]

**Comment by dalehenrich** [comment]
Hello @laheadle  --- I think that you should be using [GsDevKit_home](https://github.com/GsDevKit/GsDevKit_home) not gsDevKitHome (I know that might be confusing)... and there is already an [open issue for this](https://github.com/GsDevKit/GsDevKit_home/issues/131), including a [patch](https://github.com/GsDevKit/GsDevKit_home/issues/131#issuecomment-230523655) ... I think there are more places that ulimately need to be patched, but this is the spot that @MFeldtmann noted ...

**Comment by laheadle** [comment]
Thanks Dale, Makes sense!
